"""Protocols for the small Browser Use surface consumed by this project."""

from __future__ import annotations

from typing import Any, Protocol


class PageLike(Protocol):
    async def get_title(self) -> str: ...
    async def get_url(self) -> str: ...
    async def screenshot(self, *, format: str = "png") -> str: ...
    async def get_elements_by_css_selector(self, selector: str) -> list[Any]: ...


class BrowserSessionLike(Protocol):
    async def get_tabs(self) -> list[Any]: ...
    async def get_current_page(self) -> PageLike | None: ...
    async def get_current_page_url(self) -> str: ...
    async def get_current_page_title(self) -> str: ...
    async def new_page(self, url: str) -> PageLike: ...
    async def start(self) -> Any: ...
    async def stop(self) -> Any: ...
